### ISSUE TITLE
为什么我的小米max3特别的卡顿？完全没有rn 流畅？

### ISSUE THREAD

**Issue by homieblog** [GanZhiXiong/GZXTaoBaoAppFlutter#11]
为什么我的小米max3特别的卡顿？完全没有rn 流畅？

**Comment by GanZhiXiong** [comment]
release下还是debug下？

**Comment by homieblog** [comment]
> release下还是debug下？

我是直接扫那个android 的二维码下载的app啊？肯定是release吧

**Comment by homieblog** [comment]
> release下还是debug下？

我觉得真的没有想象的流畅，同样用华为mate20 测试了一下  感觉也有点丢帧，不过会好很多

**Comment by GanZhiXiong** [comment]
这个App是快速完成的，目前商品列表会有点不是很流畅，还有待优化。
我没做rn版，无法对比，正常情况下，肯定会比rn流畅的。

**Comment by Lizhooh** [comment]
me too，是 dart 底层的问题，上层做优化也没啥用。
