### ISSUE TITLE
首页布局问题

### ISSUE THREAD

**Issue by 370966584** [GanZhiXiong/GZXTaoBaoAppFlutter#14]
![image](https://user-images.githubusercontent.com/26058251/59832646-f5286500-9376-11e9-9764-262c37f8ad8e.png)
请问下这里为什么要用Offstage包裹一下， offstage =true 不是吧控件隐藏了吗？

还有这里
![image](https://user-images.githubusercontent.com/26058251/59832886-83045000-9377-11e9-9305-a792cde8646d.png)

NestedScrollview为什么还要 在添加一次  顶部的布局v

**Comment by fg2q1q3q** [comment]
虽然我的项目没有运行起来，不过我看博主的代码同样有这个疑问，我给自己的解释是：博主改动布局的时候遗漏了，这几行代码其实并没啥用。
不过你截取的第二段代码应该是没毛病的，只有把这一大串v放在flexXXX里面，中间那部分滚动的时候才能固定下来，实际上appbar是非常非常长的

**Comment by 370966584** [comment]
> 虽然我的项目没有运行起来，不过我看博主的代码同样有这个疑问，我给自己的解释是：博主改动布局的时候遗漏了，这几行代码其实并没啥用

我也还没运行项目，我只是安装了下apk,  对比一下看源码，手机弄得发烫没咱也不敢问😆

**Comment by fg2q1q3q** [comment]
还好还好，学到不少东西呢，感谢博主，我主要是断网一个月，手机开热点依赖下不动所以跑不起来，尴尬
