### ISSUE TITLE
内部有冗余代码,作者希望别人帮你维护下吗?

### ISSUE THREAD

**Issue by Jinxishihenian** [GanZhiXiong/GZXTaoBaoAppFlutter#28]
![深度截图_选择区域_20191029164641](https://user-images.githubusercontent.com/44466363/67751288-caa89000-fa6b-11e9-942d-210efae1f0fe.png)

**Comment by GanZhiXiong** [comment]
最近工作比较忙，没有时间重构代码啊哈! 
欢迎大家一起维护，你也可以发起PR!
