### ISSUE TITLE
商品列表滑动到顶部后，之后往上滑，头部不会出来

### ISSUE THREAD

**Issue by wanglianghai** [GanZhiXiong/GZXTaoBaoAppFlutter#3]

**Comment by hrongyong** [comment]
滑动事件冲突了吧

**Comment by webzmj530** [comment]
他这个是两个滚动容器吧

**Comment by fg2q1q3q** [comment]
连个代码都没有你们都能评论这么嗨

**Comment by wanglianghai** [comment]
哈哈

**Comment by webzmj530** [comment]
老哥 是小弟的错 不敢妄加评论

**Comment by GanZhiXiong** [comment]
这个bug我会尽快解决！
代码尚有不规范等，还需时间整理，会尽快开源！

**Comment by GanZhiXiong** [comment]
这个问题已修复，请安装最新版！
V1.0.1 release notes
添加APP更新功能
跳转的页面需要显示键盘则去掉跳转动画
修复首页商品列表和头部滚动冲突的问题
优化性能、美化界面
点击设置按钮可以显示当前版本号

![image](https://user-images.githubusercontent.com/27394631/58970566-47e91500-87ec-11e9-8012-9236d1ccedba.png)
